kafka:
  bootstrapAddress: http://localhost:9092
  topics:
    msgTransactions:
      name: transactions
  streams:
    applicationId: transactionsApplication
    stateStoreName: transactionsStore
jwt:
  secret: synpulse
  expirationDateInMs: 600000